// Bordercross — geographic dataset
//
// COUNTRIES: [isoAlpha2, name, lat, lon, aliases[]]
//   lat/lon are approximate centroids, used for the route map and as a
//   last-resort proximity fallback in graph.js. They are not survey-grade.
//
// LAND_EDGES: undirected pairs of countries that share a land border.
// SEA_EDGES: undirected pairs that don't share a land border but are
//   connected by a well-known short sea crossing, strait, or ferry route
//   (a small number of longer "gateway" links — e.g. Australia–New Zealand,
//   Iceland–UK — are included too, because otherwise those nations would
//   have no route into the rest of the world at all; see README).
//
// Both edge lists are symmetrized when the graph is built, so each pair
// only needs to be listed once.

export const COUNTRIES = [
  ["CA", "Canada", 56.1, -106.3],
  ["US", "United States", 39.8, -98.6, ["usa", "united states of america", "america"]],
  ["MX", "Mexico", 23.6, -102.5],
  ["GT", "Guatemala", 15.8, -90.2],
  ["BZ", "Belize", 17.2, -88.5],
  ["HN", "Honduras", 15.2, -86.2],
  ["SV", "El Salvador", 13.8, -88.9],
  ["NI", "Nicaragua", 12.9, -85.2],
  ["CR", "Costa Rica", 9.7, -83.8],
  ["PA", "Panama", 8.5, -80.8],

  ["HT", "Haiti", 18.9, -72.3],
  ["DO", "Dominican Republic", 18.7, -70.2],
  ["CU", "Cuba", 21.5, -77.8],
  ["JM", "Jamaica", 18.1, -77.3],
  ["BS", "Bahamas", 24.3, -76.6],
  ["BB", "Barbados", 13.2, -59.5],
  ["TT", "Trinidad and Tobago", 10.7, -61.2],
  ["GD", "Grenada", 12.1, -61.7],
  ["LC", "Saint Lucia", 13.9, -60.9],
  ["VC", "Saint Vincent and the Grenadines", 13.0, -61.2],
  ["AG", "Antigua and Barbuda", 17.1, -61.8],
  ["KN", "Saint Kitts and Nevis", 17.3, -62.7],
  ["DM", "Dominica", 15.4, -61.4],

  ["CO", "Colombia", 4.6, -74.3],
  ["VE", "Venezuela", 8.0, -66.0],
  ["GY", "Guyana", 4.9, -58.9],
  ["SR", "Suriname", 4.1, -56.0],
  ["BR", "Brazil", -10.3, -53.2],
  ["EC", "Ecuador", -1.8, -78.2],
  ["PE", "Peru", -9.2, -75.0],
  ["BO", "Bolivia", -16.7, -64.6],
  ["PY", "Paraguay", -23.4, -58.4],
  ["CL", "Chile", -35.7, -71.5],
  ["AR", "Argentina", -38.4, -63.6],
  ["UY", "Uruguay", -32.5, -55.8],

  ["IS", "Iceland", 64.9, -19.0],
  ["IE", "Ireland", 53.4, -8.2],
  ["GB", "United Kingdom", 54.0, -2.9, ["uk", "great britain", "britain", "england"]],
  ["PT", "Portugal", 39.6, -8.2],
  ["ES", "Spain", 40.0, -3.7],
  ["FR", "France", 46.6, 2.2],
  ["AD", "Andorra", 42.5, 1.5],
  ["MC", "Monaco", 43.7, 7.4],
  ["IT", "Italy", 42.8, 12.6],
  ["SM", "San Marino", 43.9, 12.4],
  ["VA", "Vatican City", 41.9, 12.45, ["vatican", "holy see"]],
  ["CH", "Switzerland", 46.8, 8.2],
  ["LI", "Liechtenstein", 47.2, 9.5],
  ["AT", "Austria", 47.6, 14.6],
  ["DE", "Germany", 51.2, 10.4],
  ["NL", "Netherlands", 52.1, 5.3, ["holland"]],
  ["BE", "Belgium", 50.6, 4.5],
  ["LU", "Luxembourg", 49.8, 6.1],
  ["DK", "Denmark", 56.0, 9.5],
  ["PL", "Poland", 52.0, 19.5],
  ["CZ", "Czechia", 49.8, 15.5, ["czech republic"]],
  ["SK", "Slovakia", 48.7, 19.5],
  ["HU", "Hungary", 47.2, 19.5],
  ["SI", "Slovenia", 46.1, 14.8],
  ["HR", "Croatia", 45.3, 16.4],
  ["BA", "Bosnia and Herzegovina", 44.2, 17.8, ["bosnia"]],
  ["RS", "Serbia", 44.2, 20.9],
  ["ME", "Montenegro", 42.7, 19.4],
  ["XK", "Kosovo", 42.6, 20.9],
  ["AL", "Albania", 41.2, 20.2],
  ["MK", "North Macedonia", 41.6, 21.7, ["macedonia"]],
  ["BG", "Bulgaria", 42.7, 25.5],
  ["RO", "Romania", 45.9, 24.9],
  ["MD", "Moldova", 47.2, 28.5],
  ["UA", "Ukraine", 48.4, 31.2],
  ["BY", "Belarus", 53.7, 27.9],
  ["LT", "Lithuania", 55.3, 23.9],
  ["LV", "Latvia", 56.9, 24.6],
  ["EE", "Estonia", 58.6, 25.0],
  ["RU", "Russia", 61.5, 105.3, ["russian federation"]],
  ["NO", "Norway", 61.0, 8.8],
  ["SE", "Sweden", 62.0, 15.0],
  ["FI", "Finland", 64.0, 26.0],
  ["GR", "Greece", 39.1, 21.8],
  ["TR", "Turkey", 38.9, 35.2, ["turkiye"]],
  ["CY", "Cyprus", 35.1, 33.4],
  ["MT", "Malta", 35.9, 14.4],

  ["GE", "Georgia", 42.3, 43.4],
  ["AM", "Armenia", 40.1, 45.0],
  ["AZ", "Azerbaijan", 40.4, 47.6],
  ["IR", "Iran", 32.4, 53.7, ["persia"]],
  ["IQ", "Iraq", 33.2, 43.7],
  ["SY", "Syria", 34.8, 39.0],
  ["LB", "Lebanon", 33.9, 35.9],
  ["IL", "Israel", 31.0, 34.9],
  ["PS", "Palestine", 31.9, 35.2],
  ["JO", "Jordan", 30.6, 36.2],
  ["SA", "Saudi Arabia", 23.9, 45.1],
  ["KW", "Kuwait", 29.3, 47.7],
  ["QA", "Qatar", 25.3, 51.2],
  ["AE", "United Arab Emirates", 23.4, 53.8, ["uae"]],
  ["OM", "Oman", 21.5, 55.9],
  ["YE", "Yemen", 15.6, 47.6],
  ["BH", "Bahrain", 26.0, 50.5],

  ["EG", "Egypt", 26.8, 30.8],
  ["LY", "Libya", 26.3, 17.2],
  ["TN", "Tunisia", 34.0, 9.5],
  ["DZ", "Algeria", 28.0, 2.6],
  ["MA", "Morocco", 31.8, -7.1],
  ["MR", "Mauritania", 20.3, -10.3],

  ["ML", "Mali", 17.6, -4.0],
  ["NE", "Niger", 17.6, 8.1],
  ["NG", "Nigeria", 9.1, 8.7],
  ["BJ", "Benin", 9.3, 2.3],
  ["TG", "Togo", 8.6, 1.0],
  ["GH", "Ghana", 7.9, -1.0],
  ["CI", "Cote d'Ivoire", 7.5, -5.5, ["ivory coast"]],
  ["BF", "Burkina Faso", 12.2, -1.6],
  ["GN", "Guinea", 10.4, -10.9],
  ["GW", "Guinea-Bissau", 12.0, -15.2],
  ["SN", "Senegal", 14.5, -14.5],
  ["GM", "Gambia", 13.4, -15.3],
  ["SL", "Sierra Leone", 8.5, -11.8],
  ["LR", "Liberia", 6.4, -9.4],
  ["CV", "Cape Verde", 16.0, -24.0, ["cabo verde"]],

  ["TD", "Chad", 15.5, 19.0],
  ["CF", "Central African Republic", 6.6, 20.9, ["car"]],
  ["CM", "Cameroon", 5.7, 12.7],
  ["CG", "Congo", -0.6, 15.8, ["republic of the congo", "congo-brazzaville"]],
  ["GA", "Gabon", -0.6, 11.6],
  ["GQ", "Equatorial Guinea", 1.6, 10.5],
  ["CD", "DR Congo", -2.9, 23.6, ["democratic republic of the congo", "congo-kinshasa", "dr congo", "drc", "zaire"]],
  ["ST", "Sao Tome and Principe", 0.3, 6.6],
  ["AO", "Angola", -12.3, 17.5],

  ["SD", "Sudan", 15.6, 30.2],
  ["SS", "South Sudan", 7.3, 30.0],
  ["ER", "Eritrea", 15.4, 39.0],
  ["DJ", "Djibouti", 11.8, 42.6],
  ["ET", "Ethiopia", 9.1, 40.5],
  ["SO", "Somalia", 5.2, 46.2],
  ["KE", "Kenya", 0.5, 37.9],
  ["UG", "Uganda", 1.4, 32.3],
  ["RW", "Rwanda", -1.9, 29.9],
  ["BI", "Burundi", -3.4, 29.9],
  ["TZ", "Tanzania", -6.4, 34.9],
  ["MG", "Madagascar", -18.8, 46.9],
  ["MU", "Mauritius", -20.3, 57.6],
  ["SC", "Seychelles", -4.6, 55.5],
  ["KM", "Comoros", -11.9, 43.9],

  ["ZM", "Zambia", -13.1, 27.8],
  ["MW", "Malawi", -13.3, 34.3],
  ["MZ", "Mozambique", -18.7, 35.5],
  ["ZW", "Zimbabwe", -19.0, 29.9],
  ["BW", "Botswana", -22.3, 24.7],
  ["NA", "Namibia", -22.9, 18.5],
  ["ZA", "South Africa", -30.6, 22.9],
  ["SZ", "Eswatini", -26.5, 31.5, ["swaziland"]],
  ["LS", "Lesotho", -29.6, 28.2],

  ["KZ", "Kazakhstan", 48.0, 66.9],
  ["UZ", "Uzbekistan", 41.4, 64.6],
  ["TM", "Turkmenistan", 38.9, 59.6],
  ["KG", "Kyrgyzstan", 41.2, 74.8],
  ["TJ", "Tajikistan", 38.9, 71.3],
  ["AF", "Afghanistan", 33.9, 67.7],

  ["PK", "Pakistan", 30.4, 69.3],
  ["IN", "India", 22.0, 79.0],
  ["NP", "Nepal", 28.4, 84.1],
  ["BT", "Bhutan", 27.5, 90.4],
  ["BD", "Bangladesh", 23.7, 90.4],
  ["LK", "Sri Lanka", 7.9, 80.8],
  ["MV", "Maldives", 3.2, 73.2],

  ["CN", "China", 35.9, 104.2],
  ["MN", "Mongolia", 46.9, 103.8],
  ["KP", "North Korea", 40.3, 127.5, ["dprk"]],
  ["KR", "South Korea", 36.5, 127.9, ["republic of korea"]],
  ["JP", "Japan", 36.2, 138.3],
  ["TW", "Taiwan", 23.7, 121.0],

  ["MM", "Myanmar", 21.9, 96.0, ["burma"]],
  ["LA", "Laos", 19.9, 102.5],
  ["TH", "Thailand", 15.9, 101.0],
  ["VN", "Vietnam", 16.0, 108.0],
  ["KH", "Cambodia", 12.6, 105.0],
  ["MY", "Malaysia", 4.2, 102.0],
  ["SG", "Singapore", 1.35, 103.8],
  ["BN", "Brunei", 4.5, 114.7],
  ["ID", "Indonesia", -2.5, 118.0],
  ["TL", "Timor-Leste", -8.9, 125.7, ["east timor"]],
  ["PH", "Philippines", 12.9, 121.8],
  ["PG", "Papua New Guinea", -6.3, 143.9],

  ["AU", "Australia", -25.3, 133.8],
  ["NZ", "New Zealand", -41.0, 174.9],
  ["FJ", "Fiji", -17.7, 178.0],
  ["PW", "Palau", 7.5, 134.6],
  ["FM", "Micronesia", 6.9, 158.2, ["federated states of micronesia"]],
  ["MH", "Marshall Islands", 7.1, 171.2],
  ["NR", "Nauru", -0.5, 166.9],
  ["KI", "Kiribati", 1.3, 173.0],
  ["TV", "Tuvalu", -7.1, 179.2],
  ["WS", "Samoa", -13.8, -172.1],
  ["TO", "Tonga", -21.2, -175.2],
  ["VU", "Vanuatu", -15.4, 166.9],
  ["SB", "Solomon Islands", -9.6, 160.2],
];

// Undirected land-border pairs.
export const LAND_EDGES = [
  ["CA","US"],["US","MX"],["MX","GT"],["MX","BZ"],["GT","BZ"],["GT","HN"],["GT","SV"],
  ["HN","SV"],["HN","NI"],["NI","CR"],["CR","PA"],["PA","CO"],
  ["HT","DO"],
  ["CO","VE"],["CO","EC"],["CO","PE"],["CO","BR"],["VE","GY"],["VE","BR"],["GY","SR"],["GY","BR"],
  ["SR","BR"],["BR","PE"],["BR","BO"],["BR","PY"],["BR","AR"],["BR","UY"],["EC","PE"],["PE","BO"],
  ["PE","CL"],["BO","PY"],["BO","AR"],["BO","CL"],["PY","AR"],["CL","AR"],["AR","UY"],
  ["IE","GB"],["PT","ES"],["ES","FR"],["ES","AD"],["FR","AD"],["FR","MC"],["FR","IT"],["FR","CH"],
  ["FR","DE"],["FR","BE"],["FR","LU"],["IT","CH"],["IT","AT"],["IT","SI"],["IT","SM"],["IT","VA"],
  ["CH","DE"],["CH","AT"],["CH","LI"],["LI","AT"],["AT","DE"],["AT","CZ"],["AT","SK"],["AT","HU"],
  ["AT","SI"],["DE","CZ"],["DE","PL"],["DE","DK"],["DE","NL"],["DE","BE"],["DE","LU"],["NL","BE"],
  ["BE","LU"],["PL","CZ"],["PL","SK"],["PL","UA"],["PL","BY"],["PL","LT"],["PL","RU"],["CZ","SK"],
  ["SK","UA"],["SK","HU"],["HU","UA"],["HU","RO"],["HU","RS"],["HU","HR"],["HU","SI"],["SI","HR"],
  ["HR","BA"],["HR","RS"],["HR","ME"],["BA","RS"],["BA","ME"],["RS","RO"],["RS","BG"],["RS","MK"],
  ["RS","XK"],["RS","ME"],["ME","XK"],["ME","AL"],["XK","AL"],["XK","MK"],["AL","MK"],["AL","GR"],
  ["MK","BG"],["MK","GR"],["BG","RO"],["BG","GR"],["BG","TR"],["RO","MD"],["RO","UA"],["MD","UA"],
  ["UA","RU"],["UA","BY"],["BY","LT"],["BY","LV"],["BY","RU"],["LT","LV"],["LT","RU"],["LV","EE"],
  ["LV","RU"],["EE","RU"],["RU","NO"],["RU","FI"],["RU","GE"],["RU","AZ"],["RU","KZ"],["RU","MN"],
  ["RU","CN"],["RU","KP"],["NO","SE"],["NO","FI"],["SE","FI"],["GR","TR"],["TR","GE"],["TR","AM"],
  ["TR","AZ"],["TR","IR"],["TR","IQ"],["TR","SY"],
  ["GE","AM"],["GE","AZ"],["AM","AZ"],["AM","IR"],["AZ","IR"],["IR","TM"],["IR","AF"],["IR","PK"],
  ["IR","IQ"],["IQ","KW"],["IQ","SA"],["IQ","JO"],["IQ","SY"],["SY","JO"],["SY","LB"],["SY","IL"],
  ["LB","IL"],["IL","JO"],["IL","EG"],["IL","PS"],["JO","SA"],["JO","PS"],["SA","KW"],["SA","QA"],
  ["SA","AE"],["SA","OM"],["SA","YE"],["AE","OM"],["OM","YE"],["EG","LY"],["EG","SD"],["LY","TN"],
  ["LY","DZ"],["LY","NE"],["LY","TD"],["LY","SD"],["TN","DZ"],["DZ","MA"],["DZ","MR"],["DZ","ML"],
  ["DZ","NE"],["MA","MR"],
  ["MR","ML"],["MR","SN"],["ML","SN"],["ML","GN"],["ML","CI"],["ML","BF"],["ML","NE"],["NE","NG"],
  ["NE","BJ"],["NE","BF"],["NE","TD"],["NG","BJ"],["NG","TD"],["NG","CM"],["BJ","TG"],["BJ","BF"],
  ["TG","GH"],["TG","BF"],["GH","CI"],["GH","BF"],["CI","GN"],["CI","LR"],["CI","BF"],["GN","GW"],
  ["GN","SN"],["GN","LR"],["GN","SL"],["GW","SN"],["SN","GM"],["SL","LR"],
  ["TD","CF"],["TD","CM"],["TD","SD"],["CF","CM"],["CF","CG"],["CF","CD"],["CF","SD"],["CF","SS"],
  ["CM","CG"],["CM","GA"],["CM","GQ"],["CG","GA"],["CG","CD"],["CG","AO"],["GA","GQ"],["CD","SS"],
  ["CD","UG"],["CD","RW"],["CD","BI"],["CD","TZ"],["CD","ZM"],["CD","AO"],
  ["SD","SS"],["SD","ET"],["SD","ER"],["SS","ET"],["SS","KE"],["SS","UG"],["SS","CF"],["ET","ER"],
  ["ET","DJ"],["ET","SO"],["ET","KE"],["ER","DJ"],["DJ","SO"],["SO","KE"],["KE","UG"],["KE","TZ"],
  ["UG","TZ"],["UG","RW"],["TZ","RW"],["TZ","BI"],["TZ","ZM"],["TZ","MW"],["TZ","MZ"],["RW","BI"],
  ["ZM","MW"],["ZM","ZW"],["ZM","BW"],["ZM","NA"],["ZM","AO"],["MW","MZ"],["MZ","ZW"],["MZ","ZA"],
  ["MZ","SZ"],["ZW","ZA"],["ZW","BW"],["BW","ZA"],["BW","NA"],["NA","ZA"],["NA","AO"],["ZA","SZ"],
  ["ZA","LS"],
  ["KZ","CN"],["KZ","KG"],["KZ","UZ"],["KZ","TM"],["UZ","KG"],["UZ","TJ"],["UZ","AF"],["UZ","TM"],
  ["KG","TJ"],["KG","CN"],["TJ","AF"],["TJ","CN"],["AF","CN"],["AF","PK"],
  ["PK","CN"],["PK","IN"],["IN","CN"],["IN","NP"],["IN","BT"],["IN","BD"],["IN","MM"],["NP","CN"],
  ["BT","CN"],["BD","MM"],
  ["CN","MN"],["CN","KP"],["CN","LA"],["CN","VN"],["KP","KR"],
  ["LA","MM"],["LA","TH"],["LA","KH"],["LA","VN"],["VN","KH"],["TH","MM"],["TH","KH"],["TH","MY"],
  ["MY","BN"],["MY","ID"],["ID","PG"],["ID","TL"],
];

// Undirected sea/strait crossings — short ferry-scale gaps between
// countries that don't share a land border, plus a few explicitly-noted
// long "gateway" links kept for playability (Iceland–UK, Australia–New
// Zealand). See README for the full rule.
export const SEA_EDGES = [
  ["GB","FR"],["ES","MA"],["IT","AL"],["IT","HR"],["IT","TN"],["IT","GR"],["IT","MT"],
  ["DK","SE"],["DK","NO"],["FI","EE"],
  ["RU","US"],["RU","JP"],["JP","KR"],
  ["TW","CN"],["TW","PH"],["PH","MY"],["MY","SG"],["ID","SG"],["ID","AU"],["PG","AU"],
  ["AU","NZ"],["NZ","FJ"],["PG","SB"],["SB","VU"],["VU","FJ"],["FJ","TO"],["FJ","WS"],
  ["FJ","TV"],["TV","KI"],["KI","NR"],["KI","MH"],["MH","FM"],["FM","PW"],["PW","PH"],
  ["CY","TR"],["LK","IN"],["MV","LK"],
  ["BH","SA"],["SA","EG"],["DJ","YE"],
  ["CV","SN"],["ST","GQ"],["MG","MZ"],["MG","MU"],["MG","KM"],["MG","SC"],
  ["CU","US"],["CU","MX"],["CU","BS"],["CU","JM"],["CU","HT"],["BS","US"],["JM","HT"],
  ["TT","VE"],["TT","GD"],["GD","VC"],["VC","LC"],["VC","BB"],["LC","DM"],["DM","AG"],["AG","KN"],
  ["IS","GB"],
];
