// Bordercross — geographic dataset
//
// COUNTRIES: [isoAlpha2, name, lat, lon, region, aliases[]]
//   lat/lon are approximate centroids, used for the route map and as a
//   last-resort proximity fallback in graph.js. They are not survey-grade.
//   region is used only for hints (js/game.js) — a coarse, human-legible
//   grouping, not a formal geopolitical classification.
//
// LAND_EDGES: undirected pairs of countries that share a land border.
// SEA_EDGES: undirected pairs that don't share a land border but are
//   connected by a well-known short sea crossing, strait, or ferry route
//   (a small number of longer "gateway" links — e.g. Australia–New Zealand,
//   Iceland–UK — are included too, because otherwise those nations would
//   have no route into the rest of the world at all; see README).
//
// Both edge lists are symmetrized when the graph is built, so each pair
// only needs to be listed once.

export const COUNTRIES = [
  ["CA", "Canada", 56.1, -106.3, "North America"],
  ["US", "United States", 39.8, -98.6, "North America", ["usa", "united states of america", "america"]],
  ["MX", "Mexico", 23.6, -102.5, "Central America"],
  ["GT", "Guatemala", 15.8, -90.2, "Central America"],
  ["BZ", "Belize", 17.2, -88.5, "Central America"],
  ["HN", "Honduras", 15.2, -86.2, "Central America"],
  ["SV", "El Salvador", 13.8, -88.9, "Central America"],
  ["NI", "Nicaragua", 12.9, -85.2, "Central America"],
  ["CR", "Costa Rica", 9.7, -83.8, "Central America"],
  ["PA", "Panama", 8.5, -80.8, "Central America"],

  ["HT", "Haiti", 18.9, -72.3, "Caribbean"],
  ["DO", "Dominican Republic", 18.7, -70.2, "Caribbean"],
  ["CU", "Cuba", 21.5, -77.8, "Caribbean"],
  ["JM", "Jamaica", 18.1, -77.3, "Caribbean"],
  ["BS", "Bahamas", 24.3, -76.6, "Caribbean"],
  ["BB", "Barbados", 13.2, -59.5, "Caribbean"],
  ["TT", "Trinidad and Tobago", 10.7, -61.2, "Caribbean"],
  ["GD", "Grenada", 12.1, -61.7, "Caribbean"],
  ["LC", "Saint Lucia", 13.9, -60.9, "Caribbean"],
  ["VC", "Saint Vincent and the Grenadines", 13.0, -61.2, "Caribbean"],
  ["AG", "Antigua and Barbuda", 17.1, -61.8, "Caribbean"],
  ["KN", "Saint Kitts and Nevis", 17.3, -62.7, "Caribbean"],
  ["DM", "Dominica", 15.4, -61.4, "Caribbean"],

  ["CO", "Colombia", 4.6, -74.3, "South America"],
  ["VE", "Venezuela", 8.0, -66.0, "South America"],
  ["GY", "Guyana", 4.9, -58.9, "South America"],
  ["SR", "Suriname", 4.1, -56.0, "South America"],
  ["BR", "Brazil", -10.3, -53.2, "South America"],
  ["EC", "Ecuador", -1.8, -78.2, "South America"],
  ["PE", "Peru", -9.2, -75.0, "South America"],
  ["BO", "Bolivia", -16.7, -64.6, "South America"],
  ["PY", "Paraguay", -23.4, -58.4, "South America"],
  ["CL", "Chile", -35.7, -71.5, "South America"],
  ["AR", "Argentina", -38.4, -63.6, "South America"],
  ["UY", "Uruguay", -32.5, -55.8, "South America"],

  ["IS", "Iceland", 64.9, -19.0, "Northern Europe"],
  ["IE", "Ireland", 53.4, -8.2, "Northern Europe"],
  ["GB", "United Kingdom", 54.0, -2.9, "Northern Europe", ["uk", "great britain", "britain", "england"]],
  ["PT", "Portugal", 39.6, -8.2, "Southern Europe"],
  ["ES", "Spain", 40.0, -3.7, "Southern Europe"],
  ["FR", "France", 46.6, 2.2, "Western Europe"],
  ["AD", "Andorra", 42.5, 1.5, "Southern Europe"],
  ["MC", "Monaco", 43.7, 7.4, "Western Europe"],
  ["IT", "Italy", 42.8, 12.6, "Southern Europe"],
  ["SM", "San Marino", 43.9, 12.4, "Southern Europe"],
  ["VA", "Vatican City", 41.9, 12.45, "Southern Europe", ["vatican", "holy see"]],
  ["CH", "Switzerland", 46.8, 8.2, "Western Europe"],
  ["LI", "Liechtenstein", 47.2, 9.5, "Western Europe"],
  ["AT", "Austria", 47.6, 14.6, "Western Europe"],
  ["DE", "Germany", 51.2, 10.4, "Western Europe"],
  ["NL", "Netherlands", 52.1, 5.3, "Western Europe", ["holland"]],
  ["BE", "Belgium", 50.6, 4.5, "Western Europe"],
  ["LU", "Luxembourg", 49.8, 6.1, "Western Europe"],
  ["DK", "Denmark", 56.0, 9.5, "Northern Europe"],
  ["PL", "Poland", 52.0, 19.5, "Eastern Europe"],
  ["CZ", "Czechia", 49.8, 15.5, "Eastern Europe", ["czech republic"]],
  ["SK", "Slovakia", 48.7, 19.5, "Eastern Europe"],
  ["HU", "Hungary", 47.2, 19.5, "Eastern Europe"],
  ["SI", "Slovenia", 46.1, 14.8, "Southeastern Europe"],
  ["HR", "Croatia", 45.3, 16.4, "Southeastern Europe"],
  ["BA", "Bosnia and Herzegovina", 44.2, 17.8, "Southeastern Europe", ["bosnia"]],
  ["RS", "Serbia", 44.2, 20.9, "Southeastern Europe"],
  ["ME", "Montenegro", 42.7, 19.4, "Southeastern Europe"],
  ["XK", "Kosovo", 42.6, 20.9, "Southeastern Europe"],
  ["AL", "Albania", 41.2, 20.2, "Southeastern Europe"],
  ["MK", "North Macedonia", 41.6, 21.7, "Southeastern Europe", ["macedonia"]],
  ["BG", "Bulgaria", 42.7, 25.5, "Eastern Europe"],
  ["RO", "Romania", 45.9, 24.9, "Eastern Europe"],
  ["MD", "Moldova", 47.2, 28.5, "Eastern Europe"],
  ["UA", "Ukraine", 48.4, 31.2, "Eastern Europe"],
  ["BY", "Belarus", 53.7, 27.9, "Eastern Europe"],
  ["LT", "Lithuania", 55.3, 23.9, "Eastern Europe"],
  ["LV", "Latvia", 56.9, 24.6, "Eastern Europe"],
  ["EE", "Estonia", 58.6, 25.0, "Eastern Europe"],
  ["RU", "Russia", 61.5, 105.3, "Eastern Europe", ["russian federation"]],
  ["NO", "Norway", 61.0, 8.8, "Northern Europe"],
  ["SE", "Sweden", 62.0, 15.0, "Northern Europe"],
  ["FI", "Finland", 64.0, 26.0, "Northern Europe"],
  ["GR", "Greece", 39.1, 21.8, "Southern Europe"],
  ["TR", "Turkey", 38.9, 35.2, "Middle East", ["turkiye"]],
  ["CY", "Cyprus", 35.1, 33.4, "Southern Europe"],
  ["MT", "Malta", 35.9, 14.4, "Southern Europe"],

  ["GE", "Georgia", 42.3, 43.4, "Caucasus"],
  ["AM", "Armenia", 40.1, 45.0, "Caucasus"],
  ["AZ", "Azerbaijan", 40.4, 47.6, "Caucasus"],
  ["IR", "Iran", 32.4, 53.7, "Middle East", ["persia"]],
  ["IQ", "Iraq", 33.2, 43.7, "Middle East"],
  ["SY", "Syria", 34.8, 39.0, "Middle East"],
  ["LB", "Lebanon", 33.9, 35.9, "Middle East"],
  ["IL", "Israel", 31.0, 34.9, "Middle East"],
  ["PS", "Palestine", 31.9, 35.2, "Middle East"],
  ["JO", "Jordan", 30.6, 36.2, "Middle East"],
  ["SA", "Saudi Arabia", 23.9, 45.1, "Middle East"],
  ["KW", "Kuwait", 29.3, 47.7, "Middle East"],
  ["QA", "Qatar", 25.3, 51.2, "Middle East"],
  ["AE", "United Arab Emirates", 23.4, 53.8, "Middle East", ["uae"]],
  ["OM", "Oman", 21.5, 55.9, "Middle East"],
  ["YE", "Yemen", 15.6, 47.6, "Middle East"],
  ["BH", "Bahrain", 26.0, 50.5, "Middle East"],

  ["EG", "Egypt", 26.8, 30.8, "North Africa"],
  ["LY", "Libya", 26.3, 17.2, "North Africa"],
  ["TN", "Tunisia", 34.0, 9.5, "North Africa"],
  ["DZ", "Algeria", 28.0, 2.6, "North Africa"],
  ["MA", "Morocco", 31.8, -7.1, "North Africa"],
  ["MR", "Mauritania", 20.3, -10.3, "North Africa"],

  ["ML", "Mali", 17.6, -4.0, "West Africa"],
  ["NE", "Niger", 17.6, 8.1, "West Africa"],
  ["NG", "Nigeria", 9.1, 8.7, "West Africa"],
  ["BJ", "Benin", 9.3, 2.3, "West Africa"],
  ["TG", "Togo", 8.6, 1.0, "West Africa"],
  ["GH", "Ghana", 7.9, -1.0, "West Africa"],
  ["CI", "Cote d'Ivoire", 7.5, -5.5, "West Africa", ["ivory coast"]],
  ["BF", "Burkina Faso", 12.2, -1.6, "West Africa"],
  ["GN", "Guinea", 10.4, -10.9, "West Africa"],
  ["GW", "Guinea-Bissau", 12.0, -15.2, "West Africa"],
  ["SN", "Senegal", 14.5, -14.5, "West Africa"],
  ["GM", "Gambia", 13.4, -15.3, "West Africa"],
  ["SL", "Sierra Leone", 8.5, -11.8, "West Africa"],
  ["LR", "Liberia", 6.4, -9.4, "West Africa"],
  ["CV", "Cape Verde", 16.0, -24.0, "West Africa", ["cabo verde"]],

  ["TD", "Chad", 15.5, 19.0, "Central Africa"],
  ["CF", "Central African Republic", 6.6, 20.9, "Central Africa", ["car"]],
  ["CM", "Cameroon", 5.7, 12.7, "Central Africa"],
  ["CG", "Congo", -0.6, 15.8, "Central Africa", ["republic of the congo", "congo-brazzaville"]],
  ["GA", "Gabon", -0.6, 11.6, "Central Africa"],
  ["GQ", "Equatorial Guinea", 1.6, 10.5, "Central Africa"],
  ["CD", "DR Congo", -2.9, 23.6, "Central Africa", ["democratic republic of the congo", "congo-kinshasa", "dr congo", "drc", "zaire"]],
  ["ST", "Sao Tome and Principe", 0.3, 6.6, "Central Africa"],
  ["AO", "Angola", -12.3, 17.5, "Central Africa"],

  ["SD", "Sudan", 15.6, 30.2, "East Africa"],
  ["SS", "South Sudan", 7.3, 30.0, "East Africa"],
  ["ER", "Eritrea", 15.4, 39.0, "East Africa"],
  ["DJ", "Djibouti", 11.8, 42.6, "East Africa"],
  ["ET", "Ethiopia", 9.1, 40.5, "East Africa"],
  ["SO", "Somalia", 5.2, 46.2, "East Africa"],
  ["KE", "Kenya", 0.5, 37.9, "East Africa"],
  ["UG", "Uganda", 1.4, 32.3, "East Africa"],
  ["RW", "Rwanda", -1.9, 29.9, "East Africa"],
  ["BI", "Burundi", -3.4, 29.9, "East Africa"],
  ["TZ", "Tanzania", -6.4, 34.9, "East Africa"],
  ["MG", "Madagascar", -18.8, 46.9, "Indian Ocean Islands"],
  ["MU", "Mauritius", -20.3, 57.6, "Indian Ocean Islands"],
  ["SC", "Seychelles", -4.6, 55.5, "Indian Ocean Islands"],
  ["KM", "Comoros", -11.9, 43.9, "Indian Ocean Islands"],

  ["ZM", "Zambia", -13.1, 27.8, "Southern Africa"],
  ["MW", "Malawi", -13.3, 34.3, "Southern Africa"],
  ["MZ", "Mozambique", -18.7, 35.5, "Southern Africa"],
  ["ZW", "Zimbabwe", -19.0, 29.9, "Southern Africa"],
  ["BW", "Botswana", -22.3, 24.7, "Southern Africa"],
  ["NA", "Namibia", -22.9, 18.5, "Southern Africa"],
  ["ZA", "South Africa", -30.6, 22.9, "Southern Africa"],
  ["SZ", "Eswatini", -26.5, 31.5, "Southern Africa", ["swaziland"]],
  ["LS", "Lesotho", -29.6, 28.2, "Southern Africa"],

  ["KZ", "Kazakhstan", 48.0, 66.9, "Central Asia"],
  ["UZ", "Uzbekistan", 41.4, 64.6, "Central Asia"],
  ["TM", "Turkmenistan", 38.9, 59.6, "Central Asia"],
  ["KG", "Kyrgyzstan", 41.2, 74.8, "Central Asia"],
  ["TJ", "Tajikistan", 38.9, 71.3, "Central Asia"],
  ["AF", "Afghanistan", 33.9, 67.7, "Central Asia"],

  ["PK", "Pakistan", 30.4, 69.3, "South Asia"],
  ["IN", "India", 22.0, 79.0, "South Asia"],
  ["NP", "Nepal", 28.4, 84.1, "South Asia"],
  ["BT", "Bhutan", 27.5, 90.4, "South Asia"],
  ["BD", "Bangladesh", 23.7, 90.4, "South Asia"],
  ["LK", "Sri Lanka", 7.9, 80.8, "South Asia"],
  ["MV", "Maldives", 3.2, 73.2, "South Asia"],

  ["CN", "China", 35.9, 104.2, "East Asia"],
  ["MN", "Mongolia", 46.9, 103.8, "East Asia"],
  ["KP", "North Korea", 40.3, 127.5, "East Asia", ["dprk"]],
  ["KR", "South Korea", 36.5, 127.9, "East Asia", ["republic of korea"]],
  ["JP", "Japan", 36.2, 138.3, "East Asia"],
  ["TW", "Taiwan", 23.7, 121.0, "East Asia"],

  ["MM", "Myanmar", 21.9, 96.0, "Southeast Asia", ["burma"]],
  ["LA", "Laos", 19.9, 102.5, "Southeast Asia"],
  ["TH", "Thailand", 15.9, 101.0, "Southeast Asia"],
  ["VN", "Vietnam", 16.0, 108.0, "Southeast Asia"],
  ["KH", "Cambodia", 12.6, 105.0, "Southeast Asia"],
  ["MY", "Malaysia", 4.2, 102.0, "Southeast Asia"],
  ["SG", "Singapore", 1.35, 103.8, "Southeast Asia"],
  ["BN", "Brunei", 4.5, 114.7, "Southeast Asia"],
  ["ID", "Indonesia", -2.5, 118.0, "Southeast Asia"],
  ["TL", "Timor-Leste", -8.9, 125.7, "Southeast Asia", ["east timor"]],
  ["PH", "Philippines", 12.9, 121.8, "Southeast Asia"],
  ["PG", "Papua New Guinea", -6.3, 143.9, "Oceania"],

  ["AU", "Australia", -25.3, 133.8, "Oceania"],
  ["NZ", "New Zealand", -41.0, 174.9, "Oceania"],
  ["FJ", "Fiji", -17.7, 178.0, "Oceania"],
  ["PW", "Palau", 7.5, 134.6, "Oceania"],
  ["FM", "Micronesia", 6.9, 158.2, "Oceania", ["federated states of micronesia"]],
  ["MH", "Marshall Islands", 7.1, 171.2, "Oceania"],
  ["NR", "Nauru", -0.5, 166.9, "Oceania"],
  ["KI", "Kiribati", 1.3, 173.0, "Oceania"],
  ["TV", "Tuvalu", -7.1, 179.2, "Oceania"],
  ["WS", "Samoa", -13.8, -172.1, "Oceania"],
  ["TO", "Tonga", -21.2, -175.2, "Oceania"],
  ["VU", "Vanuatu", -15.4, 166.9, "Oceania"],
  ["SB", "Solomon Islands", -9.6, 160.2, "Oceania"],
];

// Undirected land-border pairs.
export const LAND_EDGES = [
  ["CA","US"],["US","MX"],["MX","GT"],["MX","BZ"],["GT","BZ"],["GT","HN"],["GT","SV"],
  ["HN","SV"],["HN","NI"],["NI","CR"],["CR","PA"],["PA","CO"],
  ["HT","DO"],
  ["CO","VE"],["CO","EC"],["CO","PE"],["CO","BR"],["VE","GY"],["VE","BR"],["GY","SR"],["GY","BR"],
  ["SR","BR"],["BR","PE"],["BR","BO"],["BR","PY"],["BR","AR"],["BR","UY"],["EC","PE"],["PE","BO"],
  ["PE","CL"],["BO","PY"],["BO","AR"],["BO","CL"],["PY","AR"],["CL","AR"],["AR","UY"],
  ["IE","GB"],["PT","ES"],["ES","FR"],["ES","AD"],["FR","AD"],["FR","MC"],["FR","IT"],["FR","CH"],
  ["FR","DE"],["FR","BE"],["FR","LU"],["IT","CH"],["IT","AT"],["IT","SI"],["IT","SM"],["IT","VA"],
  ["CH","DE"],["CH","AT"],["CH","LI"],["LI","AT"],["AT","DE"],["AT","CZ"],["AT","SK"],["AT","HU"],
  ["AT","SI"],["DE","CZ"],["DE","PL"],["DE","DK"],["DE","NL"],["DE","BE"],["DE","LU"],["NL","BE"],
  ["BE","LU"],["PL","CZ"],["PL","SK"],["PL","UA"],["PL","BY"],["PL","LT"],["PL","RU"],["CZ","SK"],
  ["SK","UA"],["SK","HU"],["HU","UA"],["HU","RO"],["HU","RS"],["HU","HR"],["HU","SI"],["SI","HR"],
  ["HR","BA"],["HR","RS"],["HR","ME"],["BA","RS"],["BA","ME"],["RS","RO"],["RS","BG"],["RS","MK"],
  ["RS","XK"],["RS","ME"],["ME","XK"],["ME","AL"],["XK","AL"],["XK","MK"],["AL","MK"],["AL","GR"],
  ["MK","BG"],["MK","GR"],["BG","RO"],["BG","GR"],["BG","TR"],["RO","MD"],["RO","UA"],["MD","UA"],
  ["UA","RU"],["UA","BY"],["BY","LT"],["BY","LV"],["BY","RU"],["LT","LV"],["LT","RU"],["LV","EE"],
  ["LV","RU"],["EE","RU"],["RU","NO"],["RU","FI"],["RU","GE"],["RU","AZ"],["RU","KZ"],["RU","MN"],
  ["RU","CN"],["RU","KP"],["NO","SE"],["NO","FI"],["SE","FI"],["GR","TR"],["TR","GE"],["TR","AM"],
  ["TR","AZ"],["TR","IR"],["TR","IQ"],["TR","SY"],
  ["GE","AM"],["GE","AZ"],["AM","AZ"],["AM","IR"],["AZ","IR"],["IR","TM"],["IR","AF"],["IR","PK"],
  ["IR","IQ"],["IQ","KW"],["IQ","SA"],["IQ","JO"],["IQ","SY"],["SY","JO"],["SY","LB"],["SY","IL"],
  ["LB","IL"],["IL","JO"],["IL","EG"],["IL","PS"],["JO","SA"],["JO","PS"],["SA","KW"],["SA","QA"],
  ["SA","AE"],["SA","OM"],["SA","YE"],["AE","OM"],["OM","YE"],["EG","LY"],["EG","SD"],["LY","TN"],
  ["LY","DZ"],["LY","NE"],["LY","TD"],["LY","SD"],["TN","DZ"],["DZ","MA"],["DZ","MR"],["DZ","ML"],
  ["DZ","NE"],["MA","MR"],
  ["MR","ML"],["MR","SN"],["ML","SN"],["ML","GN"],["ML","CI"],["ML","BF"],["ML","NE"],["NE","NG"],
  ["NE","BJ"],["NE","BF"],["NE","TD"],["NG","BJ"],["NG","TD"],["NG","CM"],["BJ","TG"],["BJ","BF"],
  ["TG","GH"],["TG","BF"],["GH","CI"],["GH","BF"],["CI","GN"],["CI","LR"],["CI","BF"],["GN","GW"],
  ["GN","SN"],["GN","LR"],["GN","SL"],["GW","SN"],["SN","GM"],["SL","LR"],
  ["TD","CF"],["TD","CM"],["TD","SD"],["CF","CM"],["CF","CG"],["CF","CD"],["CF","SD"],["CF","SS"],
  ["CM","CG"],["CM","GA"],["CM","GQ"],["CG","GA"],["CG","CD"],["CG","AO"],["GA","GQ"],["CD","SS"],
  ["CD","UG"],["CD","RW"],["CD","BI"],["CD","TZ"],["CD","ZM"],["CD","AO"],
  ["SD","SS"],["SD","ET"],["SD","ER"],["SS","ET"],["SS","KE"],["SS","UG"],["SS","CF"],["ET","ER"],
  ["ET","DJ"],["ET","SO"],["ET","KE"],["ER","DJ"],["DJ","SO"],["SO","KE"],["KE","UG"],["KE","TZ"],
  ["UG","TZ"],["UG","RW"],["TZ","RW"],["TZ","BI"],["TZ","ZM"],["TZ","MW"],["TZ","MZ"],["RW","BI"],
  ["ZM","MW"],["ZM","ZW"],["ZM","BW"],["ZM","NA"],["ZM","AO"],["MW","MZ"],["MZ","ZW"],["MZ","ZA"],
  ["MZ","SZ"],["ZW","ZA"],["ZW","BW"],["BW","ZA"],["BW","NA"],["NA","ZA"],["NA","AO"],["ZA","SZ"],
  ["ZA","LS"],
  ["KZ","CN"],["KZ","KG"],["KZ","UZ"],["KZ","TM"],["UZ","KG"],["UZ","TJ"],["UZ","AF"],["UZ","TM"],
  ["KG","TJ"],["KG","CN"],["TJ","AF"],["TJ","CN"],["AF","CN"],["AF","PK"],
  ["PK","CN"],["PK","IN"],["IN","CN"],["IN","NP"],["IN","BT"],["IN","BD"],["IN","MM"],["NP","CN"],
  ["BT","CN"],["BD","MM"],
  ["CN","MN"],["CN","KP"],["CN","LA"],["CN","VN"],["KP","KR"],
  ["LA","MM"],["LA","TH"],["LA","KH"],["LA","VN"],["VN","KH"],["TH","MM"],["TH","KH"],["TH","MY"],
  ["MY","BN"],["MY","ID"],["ID","PG"],["ID","TL"],
];

// Undirected sea/strait crossings — short ferry-scale gaps between
// countries that don't share a land border, plus a few explicitly-noted
// long "gateway" links kept for playability (Iceland–UK, Australia–New
// Zealand). See README for the full rule.
export const SEA_EDGES = [
  ["GB","FR"],["ES","MA"],["IT","AL"],["IT","HR"],["IT","TN"],["IT","GR"],["IT","MT"],
  ["DK","SE"],["DK","NO"],["FI","EE"],
  ["RU","US"],["RU","JP"],["JP","KR"],
  ["TW","CN"],["TW","PH"],["PH","MY"],["MY","SG"],["ID","SG"],["ID","AU"],["PG","AU"],
  ["AU","NZ"],["NZ","FJ"],["PG","SB"],["SB","VU"],["VU","FJ"],["FJ","TO"],["FJ","WS"],
  ["FJ","TV"],["TV","KI"],["KI","NR"],["KI","MH"],["MH","FM"],["FM","PW"],["PW","PH"],
  ["CY","TR"],["LK","IN"],["MV","LK"],
  ["BH","SA"],["SA","EG"],["DJ","YE"],
  ["CV","SN"],["ST","GQ"],["MG","MZ"],["MG","MU"],["MG","KM"],["MG","SC"],
  ["CU","US"],["CU","MX"],["CU","BS"],["CU","JM"],["CU","HT"],["BS","US"],["JM","HT"],
  ["TT","VE"],["TT","GD"],["GD","VC"],["VC","LC"],["VC","BB"],["LC","DM"],["DM","AG"],["AG","KN"],
  ["IS","GB"],
];
