name = "bordercross-scores"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "bordercross-scores"
database_id = "b79e021b-7d4f-487b-87c0-15a0be05109a"
